spring.application.name=pursuitly

spring.datasource.url=jdbc:postgresql://localhost:5433/pursuitly
spring.datasource.username=postgres
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
