spring.application.name=pursuitly

spring.datasource.url=jdbc:postgresql://localhost:5433/pursuitly
spring.datasource.username=postgres
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=yourmustbeatleast256bitsecretkeyforhmacsha256algorithm123
jwt.expiration=86400000